// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common.proto

package gophkeeperv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataType enumerates supported private data kinds.
type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_CREDENTIALS DataType = 1
	DataType_DATA_TYPE_TEXT        DataType = 2
	DataType_DATA_TYPE_BINARY      DataType = 3
	DataType_DATA_TYPE_CARD        DataType = 4
	DataType_DATA_TYPE_OTP         DataType = 5
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_CREDENTIALS",
		2: "DATA_TYPE_TEXT",
		3: "DATA_TYPE_BINARY",
		4: "DATA_TYPE_CARD",
		5: "DATA_TYPE_OTP",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_CREDENTIALS": 1,
		"DATA_TYPE_TEXT":        2,
		"DATA_TYPE_BINARY":      3,
		"DATA_TYPE_CARD":        4,
		"DATA_TYPE_OTP":         5,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// User is a registered account (no secrets in the wire model).
type User struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Login     string                 `protobuf:"bytes,2,opt,name=login,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *User) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *User) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *User) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *User) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *User) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *User) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *User) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        string
	Login     string
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Item is a private data record. Payload is already E2E-encrypted by the client.
type Item struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3"`
	xxx_hidden_Type          DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=gophkeeper.v1.DataType"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3"`
	xxx_hidden_Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Version       int64                  `protobuf:"varint,6,opt,name=version,proto3"`
	xxx_hidden_UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3"`
	xxx_hidden_Deleted       bool                   `protobuf:"varint,8,opt,name=deleted,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Item) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Item) GetOwnerId() string {
	if x != nil {
		return x.xxx_hidden_OwnerId
	}
	return ""
}

func (x *Item) GetType() DataType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *Item) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *Item) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Item) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Item) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Item) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Item) SetOwnerId(v string) {
	x.xxx_hidden_OwnerId = v
}

func (x *Item) SetType(v DataType) {
	x.xxx_hidden_Type = v
}

func (x *Item) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
}

func (x *Item) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Item) SetVersion(v int64) {
	x.xxx_hidden_Version = v
}

func (x *Item) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Item) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
}

func (x *Item) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Item) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Item_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            string
	OwnerId       string
	Type          DataType
	EncryptedData []byte
	Metadata      map[string]string
	Version       int64
	UpdatedAt     *timestamppb.Timestamp
	Deleted       bool
}

func (b0 Item_builder) Build() *Item {
	m0 := &Item{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_OwnerId = b.OwnerId
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_EncryptedData = b.EncryptedData
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_Deleted = b.Deleted
	return m0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf0\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.gophkeeper.v1.DataTypeR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.gophkeeper.v1.Item.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x91\x01\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DATA_TYPE_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x04\x12\x11\n" +
	"\rDATA_TYPE_OTP\x10\x05B\xff\x01\x92A\xc2\x01\x12N\n" +
	"\x0eGophKeeper API\x127gRPC API for private data vault with multi-device sync.2\x031.0*\x01\x022\x10application/json:\x10application/jsonZI\n" +
	"G\n" +
	"\x06Bearer\x12=\b\x02\x12(JWT access token. Format: Bearer <token>\x1a\rAuthorization \x02Z7github.com/qutaq/gophkeeper/internal/proto;gophkeeperv1b\x06proto3"

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(DataType)(0),                 // 0: gophkeeper.v1.DataType
	(*User)(nil),                  // 1: gophkeeper.v1.User
	(*Item)(nil),                  // 2: gophkeeper.v1.Item
	nil,                           // 3: gophkeeper.v1.Item.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	4, // 0: gophkeeper.v1.User.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: gophkeeper.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: gophkeeper.v1.Item.type:type_name -> gophkeeper.v1.DataType
	3, // 3: gophkeeper.v1.Item.metadata:type_name -> gophkeeper.v1.Item.MetadataEntry
	4, // 4: gophkeeper.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
