// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: data.proto

package gophkeeperv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddItemRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=gophkeeper.v1.DataType"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3"`
	xxx_hidden_Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddItemRequest) GetType() DataType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *AddItemRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *AddItemRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AddItemRequest) SetType(v DataType) {
	x.xxx_hidden_Type = v
}

func (x *AddItemRequest) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
}

func (x *AddItemRequest) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

type AddItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type          DataType
	EncryptedData []byte
	Metadata      map[string]string
}

func (b0 AddItemRequest_builder) Build() *AddItemRequest {
	m0 := &AddItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_EncryptedData = b.EncryptedData
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type AddItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *Item                  `protobuf:"bytes,1,opt,name=item,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddItemResponse) GetItem() *Item {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *AddItemResponse) SetItem(v *Item) {
	x.xxx_hidden_Item = v
}

func (x *AddItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *AddItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type AddItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *Item
}

func (b0 AddItemResponse_builder) Build() *AddItemResponse {
	m0 := &AddItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type UpdateItemRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_EncryptedData   []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3"`
	xxx_hidden_Metadata        map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpdateItemRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *UpdateItemRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *UpdateItemRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedVersion
	}
	return 0
}

func (x *UpdateItemRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *UpdateItemRequest) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
}

func (x *UpdateItemRequest) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *UpdateItemRequest) SetExpectedVersion(v int64) {
	x.xxx_hidden_ExpectedVersion = v
}

type UpdateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            string
	EncryptedData []byte
	Metadata      map[string]string
	// expected_version enables optimistic concurrency control.
	ExpectedVersion int64
}

func (b0 UpdateItemRequest_builder) Build() *UpdateItemRequest {
	m0 := &UpdateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_EncryptedData = b.EncryptedData
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_ExpectedVersion = b.ExpectedVersion
	return m0
}

type UpdateItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *Item                  `protobuf:"bytes,1,opt,name=item,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *UpdateItemResponse) SetItem(v *Item) {
	x.xxx_hidden_Item = v
}

func (x *UpdateItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *UpdateItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type UpdateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *Item
}

func (b0 UpdateItemResponse_builder) Build() *UpdateItemResponse {
	m0 := &UpdateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DeleteItemRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type DeleteItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 DeleteItemRequest_builder) Build() *DeleteItemRequest {
	m0 := &DeleteItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DeleteItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *Item                  `protobuf:"bytes,1,opt,name=item,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteItemResponse) GetItem() *Item {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *DeleteItemResponse) SetItem(v *Item) {
	x.xxx_hidden_Item = v
}

func (x *DeleteItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *DeleteItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type DeleteItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *Item
}

func (b0 DeleteItemResponse_builder) Build() *DeleteItemResponse {
	m0 := &DeleteItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type ListItemsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type           DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=gophkeeper.v1.DataType"`
	xxx_hidden_IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListItemsRequest) GetType() DataType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *ListItemsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IncludeDeleted
	}
	return false
}

func (x *ListItemsRequest) SetType(v DataType) {
	x.xxx_hidden_Type = v
}

func (x *ListItemsRequest) SetIncludeDeleted(v bool) {
	x.xxx_hidden_IncludeDeleted = v
}

type ListItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// If set, only items of this type are returned.
	Type DataType
	// When true, soft-deleted items are included.
	IncludeDeleted bool
}

func (b0 ListItemsRequest_builder) Build() *ListItemsRequest {
	m0 := &ListItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_IncludeDeleted = b.IncludeDeleted
	return m0
}

type ListItemsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Item               `protobuf:"bytes,1,rep,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ListItemsResponse) SetItems(v []*Item) {
	x.xxx_hidden_Items = &v
}

type ListItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Item
}

func (b0 ListItemsResponse_builder) Build() *ListItemsResponse {
	m0 := &ListItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GetItemRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type GetItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 GetItemRequest_builder) Build() *GetItemRequest {
	m0 := &GetItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type GetItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *Item                  `protobuf:"bytes,1,opt,name=item,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *GetItemResponse) SetItem(v *Item) {
	x.xxx_hidden_Item = v
}

func (x *GetItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *GetItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type GetItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *Item
}

func (b0 GetItemResponse_builder) Build() *GetItemResponse {
	m0 := &GetItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\rgophkeeper.v1\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\xea\x01\n" +
	"\x0eAddItemRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.gophkeeper.v1.DataTypeR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.gophkeeper.v1.AddItemRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0fAddItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"\xfe\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12J\n" +
	"\bmetadata\x18\x03 \x03(\v2..gophkeeper.v1.UpdateItemRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x12UpdateItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12DeleteItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"h\n" +
	"\x10ListItemsRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.gophkeeper.v1.DataTypeR\x04type\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\">\n" +
	"\x11ListItemsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item2\x8b\x04\n" +
	"\vDataService\x12^\n" +
	"\aAddItem\x12\x1d.gophkeeper.v1.AddItemRequest\x1a\x1e.gophkeeper.v1.AddItemResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/items\x12l\n" +
	"\n" +
	"UpdateItem\x12 .gophkeeper.v1.UpdateItemRequest\x1a!.gophkeeper.v1.UpdateItemResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/items/{id}\x12i\n" +
	"\n" +
	"DeleteItem\x12 .gophkeeper.v1.DeleteItemRequest\x1a!.gophkeeper.v1.DeleteItemResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/items/{id}\x12a\n" +
	"\tListItems\x12\x1f.gophkeeper.v1.ListItemsRequest\x1a .gophkeeper.v1.ListItemsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12`\n" +
	"\aGetItem\x12\x1d.gophkeeper.v1.GetItemRequest\x1a\x1e.gophkeeper.v1.GetItemResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/items/{id}B9Z7github.com/qutaq/gophkeeper/internal/proto;gophkeeperv1b\x06proto3"

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_data_proto_goTypes = []any{
	(*AddItemRequest)(nil),     // 0: gophkeeper.v1.AddItemRequest
	(*AddItemResponse)(nil),    // 1: gophkeeper.v1.AddItemResponse
	(*UpdateItemRequest)(nil),  // 2: gophkeeper.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil), // 3: gophkeeper.v1.UpdateItemResponse
	(*DeleteItemRequest)(nil),  // 4: gophkeeper.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil), // 5: gophkeeper.v1.DeleteItemResponse
	(*ListItemsRequest)(nil),   // 6: gophkeeper.v1.ListItemsRequest
	(*ListItemsResponse)(nil),  // 7: gophkeeper.v1.ListItemsResponse
	(*GetItemRequest)(nil),     // 8: gophkeeper.v1.GetItemRequest
	(*GetItemResponse)(nil),    // 9: gophkeeper.v1.GetItemResponse
	nil,                        // 10: gophkeeper.v1.AddItemRequest.MetadataEntry
	nil,                        // 11: gophkeeper.v1.UpdateItemRequest.MetadataEntry
	(DataType)(0),              // 12: gophkeeper.v1.DataType
	(*Item)(nil),               // 13: gophkeeper.v1.Item
}
var file_data_proto_depIdxs = []int32{
	12, // 0: gophkeeper.v1.AddItemRequest.type:type_name -> gophkeeper.v1.DataType
	10, // 1: gophkeeper.v1.AddItemRequest.metadata:type_name -> gophkeeper.v1.AddItemRequest.MetadataEntry
	13, // 2: gophkeeper.v1.AddItemResponse.item:type_name -> gophkeeper.v1.Item
	11, // 3: gophkeeper.v1.UpdateItemRequest.metadata:type_name -> gophkeeper.v1.UpdateItemRequest.MetadataEntry
	13, // 4: gophkeeper.v1.UpdateItemResponse.item:type_name -> gophkeeper.v1.Item
	13, // 5: gophkeeper.v1.DeleteItemResponse.item:type_name -> gophkeeper.v1.Item
	12, // 6: gophkeeper.v1.ListItemsRequest.type:type_name -> gophkeeper.v1.DataType
	13, // 7: gophkeeper.v1.ListItemsResponse.items:type_name -> gophkeeper.v1.Item
	13, // 8: gophkeeper.v1.GetItemResponse.item:type_name -> gophkeeper.v1.Item
	0,  // 9: gophkeeper.v1.DataService.AddItem:input_type -> gophkeeper.v1.AddItemRequest
	2,  // 10: gophkeeper.v1.DataService.UpdateItem:input_type -> gophkeeper.v1.UpdateItemRequest
	4,  // 11: gophkeeper.v1.DataService.DeleteItem:input_type -> gophkeeper.v1.DeleteItemRequest
	6,  // 12: gophkeeper.v1.DataService.ListItems:input_type -> gophkeeper.v1.ListItemsRequest
	8,  // 13: gophkeeper.v1.DataService.GetItem:input_type -> gophkeeper.v1.GetItemRequest
	1,  // 14: gophkeeper.v1.DataService.AddItem:output_type -> gophkeeper.v1.AddItemResponse
	3,  // 15: gophkeeper.v1.DataService.UpdateItem:output_type -> gophkeeper.v1.UpdateItemResponse
	5,  // 16: gophkeeper.v1.DataService.DeleteItem:output_type -> gophkeeper.v1.DeleteItemResponse
	7,  // 17: gophkeeper.v1.DataService.ListItems:output_type -> gophkeeper.v1.ListItemsResponse
	9,  // 18: gophkeeper.v1.DataService.GetItem:output_type -> gophkeeper.v1.GetItemResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
