// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sync.proto

package gophkeeperv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SinceVersion   int64                  `protobuf:"varint,1,opt,name=since_version,json=sinceVersion,proto3"`
	xxx_hidden_SinceTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since_timestamp,json=sinceTimestamp,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRequest) GetSinceVersion() int64 {
	if x != nil {
		return x.xxx_hidden_SinceVersion
	}
	return 0
}

func (x *SyncRequest) GetSinceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_SinceTimestamp
	}
	return nil
}

func (x *SyncRequest) SetSinceVersion(v int64) {
	x.xxx_hidden_SinceVersion = v
}

func (x *SyncRequest) SetSinceTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_SinceTimestamp = v
}

func (x *SyncRequest) HasSinceTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SinceTimestamp != nil
}

func (x *SyncRequest) ClearSinceTimestamp() {
	x.xxx_hidden_SinceTimestamp = nil
}

type SyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// since_version is the exclusive lower bound of item versions to return.
	SinceVersion int64
	// since_timestamp is an optional alternative cursor (items with updated_at > value).
	SinceTimestamp *timestamppb.Timestamp
}

func (b0 SyncRequest_builder) Build() *SyncRequest {
	m0 := &SyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SinceVersion = b.SinceVersion
	x.xxx_hidden_SinceTimestamp = b.SinceTimestamp
	return m0
}

type SyncResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Item               `protobuf:"bytes,1,rep,name=items,proto3"`
	xxx_hidden_ServerVersion int64                  `protobuf:"varint,2,opt,name=server_version,json=serverVersion,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncResponse) GetItems() []*Item {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *SyncResponse) GetServerVersion() int64 {
	if x != nil {
		return x.xxx_hidden_ServerVersion
	}
	return 0
}

func (x *SyncResponse) SetItems(v []*Item) {
	x.xxx_hidden_Items = &v
}

func (x *SyncResponse) SetServerVersion(v int64) {
	x.xxx_hidden_ServerVersion = v
}

type SyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Item
	// server_version is the highest item version among returned (or known) items.
	ServerVersion int64
}

func (b0 SyncResponse_builder) Build() *SyncResponse {
	m0 := &SyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_ServerVersion = b.ServerVersion
	return m0
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\rgophkeeper.v1\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\vSyncRequest\x12#\n" +
	"\rsince_version\x18\x01 \x01(\x03R\fsinceVersion\x12C\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0esinceTimestamp\"`\n" +
	"\fSyncResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\x03R\rserverVersion2c\n" +
	"\vSyncService\x12T\n" +
	"\x04Sync\x12\x1a.gophkeeper.v1.SyncRequest\x1a\x1b.gophkeeper.v1.SyncResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/syncB9Z7github.com/qutaq/gophkeeper/internal/proto;gophkeeperv1b\x06proto3"

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_proto_goTypes = []any{
	(*SyncRequest)(nil),           // 0: gophkeeper.v1.SyncRequest
	(*SyncResponse)(nil),          // 1: gophkeeper.v1.SyncResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Item)(nil),                  // 3: gophkeeper.v1.Item
}
var file_sync_proto_depIdxs = []int32{
	2, // 0: gophkeeper.v1.SyncRequest.since_timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: gophkeeper.v1.SyncResponse.items:type_name -> gophkeeper.v1.Item
	0, // 2: gophkeeper.v1.SyncService.Sync:input_type -> gophkeeper.v1.SyncRequest
	1, // 3: gophkeeper.v1.SyncService.Sync:output_type -> gophkeeper.v1.SyncResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
